language: node_js

# workaround for obsolete `temp` module 0.6
env:
  global:
    - TMPDIR=/tmp

node_js:
 - '0.10'
 - '0.12'
 - iojs

services:
 - memcached

notifications:
  email:
    jrgm@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm install -g npm@2
  - npm config set spin false

script:
  - npm run outdated
  - ./node_modules/.bin/grunt validate-shrinkwrap --force
  - npm test
